language: php
php:
  - 5.6
  - 7.0
before_script:
  - echo 'date.timezone = "UTC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install
script:
  - ./vendor/bin/phpunit --configuration ./tests/phpunit.xml